# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [ ]:
import numpy as np

In [1]:
# Tu respuesta aquí
nombre = "Diana Marcela Tuberquia Lozano"
edad = 39
print("Mi nombre es", nombre, "y tengo", edad, "años.")

Mi nombre es Diana Marcela Tuberquia Lozano y tengo 39 años.


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [2]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
mostrar_1er = numeros[0]
print(f"El primer número de la lista es {mostrar_1er}") 
print("--------------")
mostrar_ultimo = numeros[-1]
print(f"El último número de la lista es {mostrar_ultimo}") 
print("--------------")
slicing = numeros[0:3]
print(f"Los tres primeros números son {slicing}")
numeros.append(99)
numeros

El primer número de la lista es 10
--------------
El último número de la lista es 15
--------------
Los tres primeros números son [10, 25, 3]


[10, 25, 3, 47, 8, 15, 99]

**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [3]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6.0:
    print("Aprobado")
else:
    print("Reprobado")


Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [4]:
# Tu respuesta aquí
base= 5
altura = 8
calcular_area = (base * altura) / 2 
print(f"El área del triángulo es {calcular_area}")

El área del triángulo es 20.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [5]:
# Tu respuesta aquí
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista_cuadrados = []
for item in lista:
    lista_cuadrados.append(item ** 2) 
print(lista_cuadrados)



[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [9]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [10]:
# Tu respuesta aquí
arreglo = np.array([1.5, 2.5, 3.5, 4.5,])
print(f"1. Valores: {arreglo} | Shape: {arreglo.shape} | Dtype: {arreglo.dtype}")
print("--------------")

matriz_ceros = np.zeros((3, 4))
print(f"2. Ceros:\n{matriz_ceros}\nShape: {matriz_ceros.shape} | Dtype: {matriz_ceros.dtype}")
print("--------------")

arreglo_espaciado = np.linspace(0, 1, 6)
print(f"3. Linspace: {arreglo_espaciado} | Shape: {arreglo_espaciado.shape} | Dtype: {arreglo_espaciado.dtype}")  




1. Valores: [1.5 2.5 3.5 4.5] | Shape: (4,) | Dtype: float64
--------------
2. Ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4) | Dtype: float64
--------------
3. Linspace: [0.  0.2 0.4 0.6 0.8 1. ] | Shape: (6,) | Dtype: float64


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [11]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz_3x4 = a.reshape(3, 4)    
print(f"Matriz 3x4:\n{matriz_3x4}")
print(f"Valor máximo: {matriz_3x4.max()}")
print(f"Valor mínimo: {matriz_3x4.min()}")
print(f"La posición indice del máximo:{matriz_3x4.argmax()}")

Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Valor máximo: 12
Valor mínimo: 1
La posición indice del máximo:11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [12]:
# Tu respuesta aquí
arreglo1 = np.random.randint(1, 10, size=5)
print(f"Arreglo 1: {arreglo1}")
arreglo2 = np.random.randint(1, 10, size=5)
print(f"Arreglo 2: {arreglo2}")
suma = arreglo1 + arreglo2
print(f"Suma elemento por elemento: {suma}")
resta = arreglo1 - arreglo2
print(f"Resta elemento por elemento: {resta}")
multiplicacion = arreglo1 * arreglo2
print(f"Multiplicación elemento por elemento: {multiplicacion}")  


Arreglo 1: [9 3 4 5 5]
Arreglo 2: [6 5 7 8 9]
Suma elemento por elemento: [15  8 11 13 14]
Resta elemento por elemento: [ 3 -2 -3 -3 -4]
Multiplicación elemento por elemento: [54 15 28 40 45]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [13]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas_aprobadas = notas[notas >= 6.0]
print(f"Notas aprobadas: {notas_aprobadas}")

Notas aprobadas: [ 8.5  6.   9.2  7.8 10. ]
